---
group: Eternity B

env:
  path: ./instances/eternity_B.txt
  max_steps: 92

model:
  embedding_dim: 32
  res_layers: 3
  maxpool_kernel: 2
  head_layers: 2
  zero_init_residuals: false

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-5
  weight_decay: 0.0e-3

scheduler:
  warmup_steps: 1

reinforce:
  advantage: no-advantage
  entropy_weight: 1.0e-5
  total_rollouts: -1
  clip_value: 5.0

rollout_buffer:
  buffer_size: 20480  # Number of played games in a single buffer.
  batches_per_rollouts: 50  # Number of times we sample from the buffer.
  batch_size: 10240  # Number of samples in a single batch.

checkpoint: 
