---
group: Eternity B

env:
  path: ./instances/eternity_B.txt
  max_steps: 512

model:
  embedding_dim: 128
  tile_embedding_dim: 48
  backbone_layers: 4
  decoder_layers: 2
  dropout: 0.1

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 0.0e-3

scheduler:
  warmup_steps: 1

reinforce:
  advantage: no-advantage
  entropy_weight: 1.0e-5
  total_rollouts: -1
  clip_value: 5.0

rollout_buffer:
  buffer_size: 8192  # Number of played games in a single buffer.
  batches_per_rollouts: 500  # Number of times we sample from the buffer.
  batch_size: 8192  # Number of samples in a single batch.

checkpoint:
