---
group: Eternity B

env:
  path: ./instances/eternity_B.txt
  max_steps: 92

model:
  embedding_dim: 64
  res_layers: 6
  maxpool_kernel: 2
  head_layers: 4
  zero_init_residuals: false

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-3
  weight_decay: 0.0e-3

scheduler:
  warmup_steps: 1

reinforce:
  advantage: no-advantage
  entropy_weight: 1.0e-5
  total_rollouts: 1000
  clip_value: 5.0

rollout_buffer:
  buffer_size: 40_960  # Number of played games in a single buffer.
  batches_per_rollouts: 400  # Number of times we sample from the buffer.
  batch_size: 40_960  # Number of samples in a single batch.

checkpoint:
