---
group: Eternity B

env:
  path: ./instances/eternity_B.txt
  batch_size: 10000

model:
  n_channels: 16
  embedding_dim: 12
  n_heads: 1
  backbone_cnn_layers: 6
  backbone_transformer_layers: 3
  decoder_layers: 3
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-3

scheduler:
  warmup_steps: 0
  cosine_tmax: 0

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip_ac: 0.30
  ppo_clip_vf: 0.30
  value_weight: 1.0e-3
  entropy_weight: 1.0e-4

trainer:
  clip_value: 1.0
  scramble_size: 0.20

iterations:
  rollouts: 100
  epochs: -1
  batches: 100
  batch_size: 5000

checkpoint:
