---
group: Eternity B

env:
  path: ./instances/eternity_B.txt
  batch_size: 1024
  episode_length: inf

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-5
  weight_decay: 1.0e-2

loss:
  gamma: 0.995
  gae_lambda: 0.95
  ppo_clip_ac: 0.20
  ppo_clip_vf: 0.20
  value_weight: 0.01
  entropy_weight: 1.0e-1
  entropy_clip: 3.0

trainer:
  episodes: -1
  epochs: 3
  batch_size: 1024
  rollouts: 100
  reset_proportion: 0.50
  clip_value: 1.0

checkpoint:
