---
group: Eternity B

env:
  path: ./instances/eternity_B.txt
  batch_size: 256
  episode_length: inf

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-5
  weight_decay: 0.0e-2

scheduler:
  warmup_steps: 1000
  cosine_t0: 0
  cosine_tmult: 1
  eta_min: 1.0e-6

loss:
  gamma: 0.995
  gae_lambda: 0.95
  ppo_clip_ac: 0.20
  ppo_clip_vf: 0.20
  value_weight: 0.01
  entropy_weight: 1.0e-1
  entropy_clip: 3.5

trainer:
  episodes: -1
  epochs: 3
  batch_size: 256
  rollouts: 80
  reset_proportion: 0.50
  clip_value: 1.0

checkpoint:
