---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 8000

model:
  n_channels: 9
  embedding_dim: 16
  n_heads: 2
  backbone_cnn_layers: 5
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 50

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip: 0.2
  value_weight: 5.0e-1
  entropy_weight: 1.0e-2
  clip_value: 0.01

replay_buffer:
  buffer_size: 320000
  batch_size: 4000

iterations:
  rollouts: 40
  epochs: 2000
  batches: 80

checkpoint:
