---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 10000

model:
  embedding_dim: 64
  n_heads: 4
  backbone_transformer_layers: 6
  decoder_layers: 2
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-3

scheduler:
  warmup_steps: 0
  cosine_t0: 0
  cosine_tmult: 0

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip_ac: 0.30
  ppo_clip_vf: 0.30
  value_weight: 1.0e-3
  entropy_weight: 1.0e-3

trainer:
  clip_value: 1.0
  scramble_size: 0.50

iterations:
  rollouts: 60
  epochs: -1
  batches: 60
  batch_size: 5000

checkpoint:
