---
group: Normal

env:
  path: ./instances/eternity_A.txt
  max_steps: 24

model:
  n_channels: 9
  embedding_dim: 16
  n_heads: 2
  backbone_cnn_layers: 5
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 0.0e-4

scheduler:
  warmup_steps: 10

reinforce:
  advantage: max
  entropy_weight: 1.0e-4
  total_rollouts: 100
  clip_value: 0.5

rollout_buffer:
  buffer_size: 300  # Number of played games in a single buffer.
  batches_per_rollout: 200  # Number of batches sampled per rollout.
  batch_size: 300  # Number of samples in a single batch.

mcts:
  max_depth: 6  # Number of played steps to estimate the value of an action.
  n_simulations: 2  # Number of simulation iterations.
  n_env_copies: 100  # Number of parallel copies of each instance.

checkpoint:
