---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 1000
  scramble_size: 1.00

model:
  embedding_dim: 12
  n_heads: 1
  backbone_layers: 6
  decoder_layers: 1
  dropout: 0.00

optimizer:
  optimizer: adamw
  learning_rate: 3.0e-4
  weight_decay: 1.0e-2

scheduler:
  warmup_steps: 0
  cosine_t0: 0
  cosine_tmult: 0

loss:
  gamma: 1.00
  gae_lambda: 0.95
  ppo_clip_ac: 0.20
  ppo_clip_vf: 0.20
  value_weight: 0.5
  entropy_weight: 1.0e-1
  no_value_function: true

trainer:
  clip_value: 1.000

iterations:
  rollouts: 60
  epochs: 15_000
  batch_size: 4000

checkpoint:
