---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 128
  scramble_size: 1.00

model:
  embedding_dim: 16
  n_heads: 1
  backbone_layers: 6
  decoder_layers: 2
  dropout: 0.00

optimizer:
  optimizer: adamw
  learning_rate: 3.0e-4
  weight_decay: 1.0e-2

loss:
  gamma: 1.00
  gae_lambda: 0.95
  ppo_clip_ac: 0.20
  ppo_clip_vf: 0.20
  value_weight: 0.01
  entropy_weight: 1.0e-1

trainer:
  episodes: -1
  epochs: 1
  batch_size: 128
  rollouts: 60
  clip_value: 1.0

checkpoint:
