---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 1000

model:
  embedding_dim: 16
  n_heads: 1
  backbone_layers: 6
  decoder_layers: 2
  dropout: 0.00

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-3

scheduler:
  warmup_steps: 0
  cosine_t0: 0
  cosine_tmult: 0

loss:
  gamma: 1.00
  gae_lambda: 0.95
  ppo_clip_ac: 0.20
  ppo_clip_vf: 0.20
  value_weight: 0.5
  entropy_weight: 1.0e-2

trainer:
  clip_value: 1.000
  scramble_size: 0.50

iterations:
  rollouts: 80
  epochs: -1
  batch_size: 8000

checkpoint:
