---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 1000

model:
  embedding_dim: 32
  n_heads: 2
  backbone_layers: 4
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-2

scheduler:
  warmup_steps: 0
  cosine_t0: 0
  cosine_tmult: 0

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip_ac: 0.30
  ppo_clip_vf: 0.30
  value_weight: 1.0e-0
  entropy_weight: 1.0e+1

trainer:
  clip_value: 1.0
  scramble_size: 0.30

iterations:
  rollouts: 60
  epochs: 10000
  batch_size: 1000

checkpoint:
