---
group: Normal

env:
  path: ./instances/eternity_A.txt
  max_steps: 64

model:
  embedding_dim: 16
  backbone_layers: 8
  decoder_layers: 4
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-3
  weight_decay: 1.0e-3

scheduler:
  warmup_steps: 10

reinforce:
  advantage: max
  entropy_weight: 1.0e-4
  total_rollouts: 10_000
  clip_value: 5.0

rollout_buffer:
  buffer_size: 2048  # Number of played games in a single buffer.
  batches_per_rollouts: 1  # Number of times we sample from the buffer.
  batch_size: 4096  # Number of samples in a single batch.

checkpoint:
