---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 600

model:
  n_channels: 16
  embedding_dim: 32
  n_heads: 4
  backbone_cnn_layers: 5
  backbone_transformer_layers: 2
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-3

scheduler:
  warmup_steps: 10

loss:
  gamma: 0.99
  value_weight: 1.0e-2
  entropy_weight: 1.0e-2
  clip_value: 0.1

replay_buffer:
  buffer_size: 1500000
  batch_size: 1000

iterations:
  rollouts: 20
  epochs: 2000
  batches: 100

treesearch:
  n_copies: 20

checkpoint:
