---
group: Normal

env:
  path: ./instances/eternity_A.txt
  batch_size: 500

model:
  n_channels: 9
  embedding_dim: 16
  n_heads: 2
  backbone_cnn_layers: 5
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-5
  weight_decay: 0.0e-4

scheduler:
  warmup_steps: 10

loss:
  gamma: 0.95
  value_weight: 1.0e-3
  entropy_weight: 1.0e-0
  clip_value: 0.01

replay_buffer:
  buffer_size: 2000000
  batch_size: 2000

iterations:
  rollouts: 20
  epochs: 500
  batches: 50

treesearch:
  n_copies: 20

checkpoint:
