---
group: Normal

env:
  path: ./instances/eternity_A.txt
  max_steps: 64

model:
  embedding_dim: 24
  n_heads: 2
  backbone_layers: 2
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-3
  weight_decay: 0.0e-4

scheduler:
  warmup_steps: 10

reinforce:
  advantage: max
  entropy_weight: 0.0e-4
  total_rollouts: 10_000
  bptt_steps: 12
  clip_value: 0.01

rollout_buffer:
  buffer_size: 384  # Number of played games in a single buffer.
  batch_size: 24576  # Number of samples in a single batch.

checkpoint:
