---
group: Normal

env:
  path: ./instances/eternity_A.txt
  max_steps: 92

model:
  n_channels: 38
  embedding_dim: 48
  n_heads: 4
  backbone_cnn_layers: 6
  backbone_transformer_layers: 1
  decoder_layers: 3
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 0.0e-4

scheduler:
  warmup_steps: 10

reinforce:
  advantage: max
  entropy_weight: 1.0e-4
  total_rollouts: -1
  clip_value: 0.5

rollout_buffer:
  buffer_size: 600  # Number of played games in a single buffer.
  batch_size: 141312  # Number of samples in a single batch.

checkpoint:
