---
group: Normal

env:
  path: ./instances/eternity_A.txt
  max_steps: 64

model:
  embedding_dim: 24
  backbone_layers: 5
  decoder_layers: 2
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 10

reinforce:
  advantage: max
  entropy_weight: 1.0e-4
  total_rollouts: 10_000
  clip_value: 5.0

rollout_buffer:
  buffer_size: 8192  # Number of played games in a single buffer.
  batch_size: 20480  # Number of samples in a single batch.

checkpoint:
