---
group: Trivial A

env:
  path: ./instances/eternity_trivial_A.txt
  batch_size: 5000

model:
  n_channels: 6
  embedding_dim: 12
  n_heads: 1
  backbone_cnn_layers: 4
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 1

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip_ac: 0.2
  ppo_clip_vf: 0.2
  value_weight: 5.0e-1
  entropy_weight: 1.0e-2

trainer:
  clip_value: 1.0
  scramble_size: 0.10

iterations:
  rollouts: 10
  epochs: 300
  batches: 10
  batch_size: 5000

checkpoint:
