---
group: Trivial A

env:
  path: ./instances/eternity_trivial_A.txt
  batch_size: 128
  episode_length: inf

optimizer:
  optimizer: adamw
  learning_rate: 3.0e-4
  weight_decay: 1.0e-2

scheduler:
  warmup_steps: 0
  cosine_t0: 100
  cosine_tmult: 1
  eta_min: 1.0e-5

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip_ac: 0.10
  ppo_clip_vf: 1.00
  value_weight: 1.0
  entropy_weight: 1.0e-2
  entropy_clip: 3.0

trainer:
  episodes: 250
  epochs: 3
  batch_size: 128
  rollouts: 10
  reset_proportion: 0.20
  clip_value: 1.0

checkpoint:
