---
group: Trivial B

env:
  path: ./instances/eternity_trivial_B.txt
  batch_size: 128
  episode_length: inf

optimizer:
  optimizer: adamw
  learning_rate: 3.0e-4
  weight_decay: 1.0e-2

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip_ac: 0.30
  ppo_clip_vf: 0.30
  value_weight: 0.1
  entropy_weight: 1.0e-1
  entropy_clip: 3.0

trainer:
  episodes: 4000
  epochs: 1
  batch_size: 128
  rollouts: 30
  reset_proportion: 0.75
  clip_value: 1.0

checkpoint:
