---
group: Trivial A

env:
  path: ./instances/eternity_trivial_A.txt
  max_steps: 8

model:
  n_channels: 6
  embedding_dim: 12
  n_heads: 2
  backbone_cnn_layers: 4
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.0

optimizer:
  learning_rate: 1.0e-2
  optimizer: adamw
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 1

reinforce:
  advantage: no-advantage
  entropy_weight: 1.0e-5
  total_rollouts: 200
  clip_value: 0.5

rollout_buffer:
  buffer_size: 2000  # Number of played games in a single buffer.
  batch_size: 16000  # Number of samples in a single batch.

checkpoint:
