group: Trivial B

env:
  path: ./instances/eternity_trivial_B.txt
  reward: win
  max_steps: 24

model:
  embedding_dim: 24
  res_layers: 3
  mlp_layers: 1
  head_layers: 3
  maxpool_kernel: 1
  zero_init_residuals: false
  use_time_embedding: true

optimizer:
  learning_rate: 5.0e-4
  optimizer: adamw
  weight_decay: 0.0e-4

scheduler:
  warmup_steps: 1

reinforce:
  advantage: estimated
  entropy_weight: 1.0e-5
  total_rollouts: 2000
  gamma: 1.00
  clip_value: 0.05
  save_every: 500

rollout_buffer:
  buffer_size: 200  # Number of played games in a single buffer.
  batches_per_rollouts: 10  # Number of times we sample from the buffer.
  batch_size: 1000  # Number of samples in a single batch.
