---
group: Trivial B

env:
  path: ./instances/eternity_trivial_B.txt
  max_steps: 24

model:
  embedding_dim: 24
  backbone_layers: 5
  decoder_layers: 2
  dropout: 0.05

optimizer:
  learning_rate: 1.0e-3
  optimizer: adamw
  weight_decay: 0.0e-3

scheduler:
  warmup_steps: 1

reinforce:
  advantage: max
  entropy_weight: 1.0e-5
  total_rollouts: 1000
  clip_value: 5.00

rollout_buffer:
  buffer_size: 1000  # Number of played games in a single buffer.
  batch_size: 16000  # Number of samples in a single batch.

checkpoint:
