---
group: Trivial B

env:
  path: ./instances/eternity_trivial_B.txt
  batch_size: 500

model:
  n_channels: 9
  embedding_dim: 16
  n_heads: 2
  backbone_cnn_layers: 4
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.05

optimizer:
  learning_rate: 1.0e-3
  optimizer: adamw
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 1

loss:
  gamma: 0.99
  value_weight: 1.0e-4
  entropy_weight: 1.0e-1
  clip_value: 1.0

replay_buffer:
  buffer_size: 50000
  batch_size: 500

iterations:
  rollouts: 10
  epochs: 2000
  batches: 100

treesearch:
  n_copies: 10

checkpoint:
