---
group: Trivial A

env:
  path: ./instances/eternity_trivial_A.txt
  batch_size: 500

model:
  n_channels: 6
  embedding_dim: 12
  n_heads: 2
  backbone_cnn_layers: 4
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.05

optimizer:
  learning_rate: 1.0e-2
  optimizer: adamw
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 1

loss:
  gamma: 0.95
  value_weight: 1.0e-2
  entropy_weight: 1.0e-5
  clip_value: 0.5

replay_buffer:
  buffer_size: 20000
  batch_size: 200

iterations:
  rollouts: 10
  epochs: 10
  batches: 100

mcts:
  n_copies: 10

checkpoint:
