---
group: Trivial A

env:
  path: ./instances/eternity_trivial_A.txt
  max_steps: 8

model:
  embedding_dim: 12
  res_layers: 4
  mlp_layers: 1
  head_layers: 1
  maxpool_kernel: 1
  zero_init_residuals: false

optimizer:
  learning_rate: 1.0e-2
  optimizer: adamw
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 1

reinforce:
  advantage: no-advantage
  entropy_weight: 1.0e-5
  total_rollouts: 200
  clip_value: 5.0

rollout_buffer:
  buffer_size: 2000  # Number of played games in a single buffer.
  batches_per_rollouts: 10  # Number of times we sample from the buffer.
  batch_size: 2000  # Number of samples in a single batch.

checkpoint:
