---
group: Trivial B

env:
  path: ./instances/eternity_trivial_B.txt
  batch_size: 5000

model:
  n_channels: 9
  embedding_dim: 16
  n_heads: 2
  backbone_cnn_layers: 4
  backbone_transformer_layers: 1
  decoder_layers: 1
  dropout: 0.05

optimizer:
  learning_rate: 1.0e-4
  optimizer: adamw
  weight_decay: 1.0e-4

scheduler:
  warmup_steps: 1

loss:
  gamma: 0.99
  gae_lambda: 0.95
  value_weight: 1.0e-2
  entropy_weight: 1.0e-2
  clip_value: 1.0

replay_buffer:
  buffer_size: 100000
  batch_size: 5000

iterations:
  rollouts: 20
  epochs: 5000
  batches: 20

checkpoint:
