group: Trivial A

env:
  path: ./instances/eternity_trivial_A.txt
  reward: win
  max_steps: 8

model:
  embedding_dim: 12
  res_layers: 4
  mlp_layers: 1
  head_layers: 1
  maxpool_kernel: 1
  zero_init_residuals: false
  use_time_embedding: true

optimizer:
  learning_rate: 1.0e-3
  optimizer: adamw
  weight_decay: 1.0e-2

scheduler:
  warmup_steps: 1

reinforce:
  advantage: estimated
  entropy_weight: 1.0e-5
  total_rollouts: 500
  gamma: 1.00
  clip_value: 5.0
  save_every: 500

rollout_buffer:
  buffer_size: 600  # Number of played games in a single buffer.
  batches_per_rollouts: 1  # Number of times we sample from the buffer.
  batch_size: 4800  # Number of samples in a single batch.
