---
group: Trivial A

env:
  path: ./instances/eternity_trivial_A.txt
  batch_size: 500
  episode_length: 10

model:
  embedding_dim: 24
  n_heads: 2
  backbone_layers: 4
  decoder_layers: 1
  dropout: 0.05

optimizer:
  optimizer: adamw
  learning_rate: 1.0e-3
  weight_decay: 1.0e-2

scheduler:
  warmup_steps: 0
  cosine_t0: 0
  cosine_tmult: 0

loss:
  gamma: 0.99
  gae_lambda: 0.95
  ppo_clip_ac: 0.10
  ppo_clip_vf: 0.20
  value_weight: 1.0e-1
  entropy_weight: 1.0e-1

trainer:
  clip_value: 1.000
  scramble_size: 0.50

iterations:
  rollouts: 10
  epochs: 300
  batch_size: 500

checkpoint:
