---
group: Trivial B

env:
  path: ./instances/eternity_trivial_B.txt
  batch_size: 128
  scramble_size: 1.00

model:
  embedding_dim: 12
  n_heads: 1
  backbone_layers: 4
  decoder_layers: 1
  dropout: 0.00

optimizer:
  learning_rate: 3.0e-4
  optimizer: adamw
  weight_decay: 1.0e-2

loss:
  gamma: 1.00
  gae_lambda: 0.95
  ppo_clip_ac: 0.30
  ppo_clip_vf: 1.00
  value_weight: 1.0
  entropy_weight: 1.0e-2

trainer:
  episodes: 250
  epochs: 3
  batch_size: 128
  rollouts: 30
  clip_value: 1.0

checkpoint:
