defaults:
  - _self_
  - trivial
group: Default group
env:
  path: ./instances/eternity_trivial_A.txt
  reward: win
  max_steps: 8
model:
  embedding_dim: 12
  n_res_layers: 4
  n_gru_layers: 1
  n_head_layers: 1
  maxpool_kernel: 1
  zero_init_residuals: false
  gru_as_mlp: false
  use_time_embedding: false
optimizer:
  learning_rate: 1.0e-3
  optimizer: adamw
  weight_decay: 0.0e-4
scheduler:
  warmup_steps: 1
reinforce:
  advantage: estimated
  gamma: 1.00
  n_total_iterations: 2000
  n_batches_per_iteration: 1
  batch_size: 600
  entropy_weight: 0.0e-5
  clip_value: 5.0
  save_every: 500
seed: 0
device: auto
distributed: []
mode: online
hydra:
  job:
    chdir: true
