group: Eternity E
env:
  path: ./instances/eternity_E.txt
  reward: delta
model:
  embedding_dim: 24
  n_layers: 4
  zero_init_residuals: false
reinforce:
  optimizer: rmsprop
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: -1
  batch_size: 500
  value_weight: 1.0e-2
  advantage: estimated
  save_every: 1000
  warmup_steps: 200
seed: 0
device: auto
hydra:
  job:
    chdir: true
