group: Eternity E
env:
  path: ./instances/eternity_E.txt
  reward: win
  max_steps: 500
model:
  embedding_dim: 24
  n_res_layers: 8
  n_gru_layers: 4
  n_head_layers: 5
  maxpool_kernel: 2
  zero_init_residuals: false
optimizer:
  learning_rate: 1.0e-5
scheduler:
  warmup_steps: 10
reinforce:
  n_total_iterations: 20000
  batch_size: 20
  clip_value: 0.005
