env:
  path: ./instances/eternity_E.txt
  reward_type: win_ratio
model:
  embedding_dim: 24
  n_layers: 3
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: 100000
  batch_size: 100
supervised:
  learning_rate: 1.0e-3
  batch_size: 128
  epoch_size: 20000
  n_epochs: 10
  test_size: 0.2
data_generation:
  n_samples: 10000
seed: 0
device: auto
