group: Eternity E
env:
  path: ./instances/eternity_E.txt
  reward: delta
model:
  embedding_dim: 64
  n_layers: 6
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: -1
  batch_size: 50
  value_weight: 1.0e-2
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
