env: ./instances/eternity_E.txt
model:
  embedding_dim: 64
  n_layers: 6
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: -1
  batch_size: 100
  value_weight: 1.0e-2
  advantage: learned
seed: 0
device: auto
