group: Eternity A
env:
  path: ./instances/eternity_A.txt
  reward: win
model:
  embedding_dim: 48
  n_res_layers: 6
  n_gru_layers: 2
  n_head_layers: 5
  maxpool_kernel: 2
  zero_init_residuals: false
optimizer:
  optimizer: adamw
  learning_rate: 1.0e-2
  weight_decay: 1.0e-4
scheduler:
  warmup_steps: 100
reinforce:
  advantage: estimated
  gamma: 1.00
  n_total_iterations: 5000
  n_batches_per_iteration: 1
  batch_size: 40000
  entropy_weight: 1.0e-5
  clip_value: 5.0
  save_every: 1000
seed: 0
device: auto
distributed: [0, 1, 2, 3, 4, 5, 6, 7]
mode: online
hydra:
  job:
    chdir: true
