group: Eternity A
env:
  path: ./instances/eternity_A.txt
  reward: delta
model:
  embedding_dim: 96
  n_res_layers: 4
  n_gru_layers: 1
  zero_init_residuals: true
reinforce:
  optimizer: adamw
  learning_rate: 1.0e-5
  warmup_steps: 1
  gamma: 0.99
  n_total_iterations: 10000
  n_batches_per_iteration: 1
  batch_size: 300
  value_weight: 1.0e-2
  entropy_weight: 1.0e-4
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
