group: Eternity A
env:
  path: ./instances/eternity_A.txt
  reward: delta
model:
  embedding_dim: 24
  n_layers: 4
  zero_init_residuals: false
reinforce:
  optimizer: rmsprop
  learning_rate: 1.0e-3
  warmup_steps: 1
  gamma: 0.99
  n_total_iterations: 10000
  n_batches_per_iteration: 5
  batch_size: 3000
  value_weight: 1.0e-2
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
