group: Eternity A
env:
  path: ./instances/eternity_A.txt
  reward: delta
model:
  embedding_dim: 24
  n_layers: 4
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  # n_batches: 60000 # ~ 200 mins
  n_batches: 20000 # ~ 60 mins
  batch_size: 200
  value_weight: 1.0e-2
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
