group: Eternity A
env:
  path: ./instances/eternity_A.txt
  reward: win
  max_steps: 64
model:
  embedding_dim: 18
  n_res_layers: 4
  n_gru_layers: 2
  n_head_layers: 3
  maxpool_kernel: 2
  zero_init_residuals: false
optimizer:
  learning_rate: 1.0e-2
scheduler:
  warmup_steps: 10
reinforce:
  n_total_iterations: 20000
  batch_size: 10000
  clip_value: 0.005
