group: Eternity A
env:
  path: ./instances/eternity_A.txt
  reward: win
  max_steps: 32
model:
  embedding_dim: 48
  n_res_layers: 6
  n_gru_layers: 2
  n_head_layers: 5
  maxpool_kernel: 2
  zero_init_residuals: false
optimizer:
  learning_rate: 1.0e-5
scheduler:
  warmup_steps: 100
reinforce:
  n_total_iterations: 5000
  batch_size: 2000
