group: Eternity A
env:
  path: ./instances/eternity_A.txt
  reward: win
model:
  embedding_dim: 92
  n_res_layers: 6
  n_gru_layers: 1
  zero_init_residuals: true
reinforce:
  optimizer: adamw
  learning_rate: 1.0e-4
  warmup_steps: 100
  gamma: 1.00
  n_total_iterations: 100000
  n_batches_per_iteration: 10
  batch_size: 300
  value_weight: 1.0e-2
  entropy_weight: 1.0e-5
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
