env: ./instances/eternity_A.txt
model:
  embedding_dim: 24
  n_layers: 4
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: 20000
  batch_size: 200
  value_weight: 1.0e-2
  advantage: learned
seed: 0
device: auto
