env:
  path: ./instances/eternity_A.txt
  reward_type: win_ratio
model:
  embedding_dim: 24
  n_layers: 3
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: 20000
  batch_size: 200
  model_path: ./logs/eternity_A-supervised-model.pt
supervised:
  learning_rate: 1.0e-4
  batch_size: 128
  epoch_size: 10000
  n_epochs: 20
  test_size: 0.2
data_generation:
  n_samples: 100000
seed: 0
device: auto
