group: Trivial A
env:
  path: ./instances/eternity_trivial_A.txt
  reward: delta
  max_steps: 4
model:
  embedding_dim: 12
  n_res_layers: 4
  n_gru_layers: 1
  n_head_layers: 1
  maxpool_kernel: 1
  zero_init_residuals: false
optimizer:
  optimizer: adamw
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
scheduler:
  warmup_steps: 1
reinforce:
  advantage: estimated
  gamma: 1.00
  n_total_iterations: 2000
  n_batches_per_iteration: 1
  batch_size: 600
  entropy_weight: 1.0e-5
  clip_value: 5.0
  save_every: 1000
seed: 0
device: auto
distributed: [auto]
mode: online
hydra:
  job:
    chdir: true
