group: Trivial B
env:
  path: ./instances/eternity_trivial_B.txt
  reward: win
  max_steps: 16
model:
  embedding_dim: 92
  n_res_layers: 4
  n_gru_layers: 1
  n_head_layers: 3
  maxpool_kernel: 2
  zero_init_residuals: true
optimizer:
  learning_rate: 1.0e-4
scheduler:
  warmup_steps: 100
reinforce:
  n_total_iterations: 100000
  batch_size: 300
