group: Trivial A
env:
  path: ./instances/eternity_trivial_A.txt
  reward: delta
model:
  embedding_dim: 12
  n_layers: 4
reinforce:
  learning_rate: 1.0e-3
  gamma: 0.99
  n_batches: 2000
  batch_size: 200
  value_weight: 1.0e-2
  advantage: learned
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
