group: Trivial B
env:
  path: ./instances/eternity_trivial_B.txt
  reward: delta
model:
  embedding_dim: 32
  n_layers: 4
  zero_init_residuals: false
reinforce:
  optimizer: rmsprop
  learning_rate: 1.0e-3
  warmup_steps: 1
  gamma: 0.99
  n_batches: 20000
  batch_size: 200
  value_weight: 1.0e-2
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
