group: Trivial B
env:
  path: ./instances/eternity_trivial_B.txt
  reward: delta
  max_steps: 64
model:
  embedding_dim: 12
  n_res_layers: 4
  n_gru_layers: 1
  n_head_layers: 3
  maxpool_kernel: 2
  zero_init_residuals: false
optimizer:
  learning_rate: 1.0e-3
scheduler:
  warmup_steps: 1
reinforce:
  n_total_iterations: 2000
  batch_size: 13000
  clip_value: 0.001
