group: Trivial B
env:
  path: ./instances/eternity_trivial_B.txt
  reward: win
model:
  embedding_dim: 92
  n_res_layers: 4
  n_gru_layers: 1
  n_head_layers: 3
  zero_init_residuals: true
optimizer:
  optimizer: adamw
  learning_rate: 1.0e-6
  weight_decay: 1.0e-4
scheduler:
  warmup_steps: 100
reinforce:
  gamma: 1.00
  n_total_iterations: 100000
  n_batches_per_iteration: 1
  batch_size: 300
  value_weight: 1.0e-2
  entropy_weight: 1.0e-2
  clip_value: 5.0
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
