group: Trivial A
env:
  path: ./instances/eternity_trivial_A.txt
  reward: win
  max_steps: 24
model:
  embedding_dim: 12
  n_res_layers: 4
  n_gru_layers: 1
  n_head_layers: 1
  maxpool_kernel: 1
  zero_init_residuals: false
optimizer:
  learning_rate: 1.0e-3
reinforce:
  advantage: estimated
  entropy_weight: 1.0e-5
  batch_size: 600
  rollout_buffer_size: 600
  n_batches_per_rollouts: 1
  n_total_rollouts: 2000
