group: Trivial B
env:
  path: ./instances/eternity_trivial_B.txt
  reward: delta
model:
  embedding_dim: 64
  n_res_layers: 4
  n_gru_layers: 1
  n_head_layers: 3
  zero_init_residuals: true
reinforce:
  optimizer: adamw
  learning_rate: 5.0e-4
  warmup_steps: 1
  gamma: 0.99
  n_total_iterations: 100000
  n_batches_per_iteration: 1
  batch_size: 300
  value_weight: 1.0e-2
  entropy_weight: 3.0e-4
  advantage: estimated
  save_every: 1000
seed: 0
device: auto
hydra:
  job:
    chdir: true
